services:
   auth:
      image: quay.io/keycloak/keycloak:18.0
      ports:
         - "8080:8080"
      environment:
         KEYCLOAK_ADMIN: admin
         KEYCLOAK_ADMIN_PASSWORD: admin
      command:
         - start-dev
         - --import-realm
      # In order to export realm data, first docker-compose up -d this file.
      # Then:
      #
      #         - export --dir /opt/keycloak/data/import --users realm_file
      volumes:
         - ./realms:/opt/keycloak/data/import
